CC = gcc
CFLAGS = -Wall -Werror -ansi -lm
WLFLG = -o

removedups: ./challenges/removedups.c
	$(CC) $(WLFLG) removedups.out ./challenges/removedups.c $(CFLAGS) && chmod 755 removedups.out

findkthlast: ./challenges/findkthlast.c
	$(CC) $(WLFLG) findkthlast.out ./challenges/findkthlast.c $(CFLAGS) && chmod 755 findkthlast.out